version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Yamboy1
  - Snazzah
  commit-message:
    prefix: chore
    include: scope
